### ISSUE TITLE
Update the project documentation

### ISSUE THREAD

**Issue by pavel-rossinsky** [pavel-rossinsky/java-a-beginners-guide-herbert-schildt#8]
## Tasks
Cover the following topics:
- [x] technical prerequisites
- [x] add the picture of the cover of the book
- [x] how to install the project on Unix-based systems
- [x] how to compile tests initially
- [x] how to compile a test after editing
- [x] how to run a test
- [x] how to uninstall the project
