### ISSUE TITLE
Integrate Maven as a build tool

### ISSUE THREAD

**Issue by pavel-rossinsky** [pavel-rossinsky/java-a-beginners-guide-herbert-schildt#9]
## Tasks:
- [x] Learn the easiest way to integrate Maven
- [x] Adapt Docker to Maven 
- [x] Add the basic version of a pom file
- [x] Find a way to run the examples one by one
- [x] Update the project documentation (will do later in #8)
